Repository 247CloudLibrary/client-admin, pull requests merged in 2022-04, with the labels that each got.

#16 axios 인스턴스 생성 및 lending.js api 함수 작성
  package-lock.json
  package.json
  src/lib/api/client.js
  src/lib/api/lending.js
Labels: enhancement

#22 lib/api/boardNotice.js에 API 함수 작성
  src/lib/api/boardNotice.js
  src/lib/api/client.js
Labels: enhancement

#32 [Libraries] API 함수 sync
  src/lib/api/libraries.js
Labels: enhancement

#35 [Books] API 함수 sync
  src/lib/api/books.js
Labels: enhancement

#33 [Board-Notice] API 함수 sync
  src/lib/api/boardNotice.js
Labels: enhancement

#34 [Board-Information] API 함수 sync
  src/lib/api/boardInformation.js
Labels: enhancement

#41 Feature/lending book list
  package-lock.json
  package.json
  src/components/LendingListForm.css
  src/components/lending/LendingListForm.js
  src/components/lending/LendingListItem.js
  src/components/lending/LendingSearchBox.js
  src/lib/api/client.js
  src/lib/api/lending.js
  src/pages/LendingPage.js
Labels: enhancement

#38 [BoardList] 폼 구성 및 간단한 css 작업
  package-lock.json
  package.json
  src/App.js
  src/components/board/BoardInfoListItem.js
  src/components/board/BoardList.js
  src/components/board/BoardMap.js
  src/components/board/BoardNoticeListItem.js
  src/components/board/BoardSideBar.js
  src/index.js
  src/pages/BoardListPage.js
  src/styles/components/board/BoardList.scss
  src/styles/components/board/BoardListItem.scss
  src/styles/components/board/BoardSideBar.scss
  src/styles/config/_reset.scss
  src/styles/style.scss
Labels: documentation, enhancement

#39 [BoardWrite] 폼 구성 및 간단한 css 작업
  package-lock.json
  package.json
  src/components/board/BoardWriteForm.js
  src/pages/BoardWritePage.js
  src/styles/components/board/BoardWriteForm.scss
Labels: documentation, enhancement

#47 [BoardEdit/Write] page파일 이름 변경 및 누락된 route설정 추가
  src/App.js
  src/pages/BoardEditPage.js
  src/styles/style.scss
Labels: enhancement

#49 Feature/draft UI
  src/components/LendingListForm.css
  src/components/lending/LendingListForm.js
  src/pages/Home.js
Labels: enhancement

#50 blacklistForm 등록
  src/components/blacklist/BlacklistForm.js
  src/components/blacklist/BlacklistItem.js
  src/pages/BlacklistPage.js
Labels: enhancement

#51 [Board] detail페이지 추가 및 board 페이지 위치 이동
  package-lock.json
  package.json
  src/App.js
  src/components/board/BoardDetail.js
  src/components/board/BoardDetailForm.js
  src/pages/board/BoardDetailPage.js
  src/pages/board/BoardEditPage.js
  src/pages/board/BoardListPage.js
  src/pages/board/BoardWritePage.js
  src/pages/board/BoardsPage.js
  src/styles/components/board/BoardDetail.scss
  src/styles/components/board/BoardDetailForm.scss
  src/styles/config/_reset.scss
  src/styles/style.scss
Labels: enhancement

#53 [Board] 코드 수정 및 통합 게시글 페이지 생성
  src/App.js
  src/components/board/BoardEditForm.js
  src/components/board/BoardInfo.js
  src/components/board/BoardList.js
  src/components/board/BoardNoticeListItem.js
  src/components/board/BoardSideBar.js
  src/components/board/BoardWriteForm.js
  src/components/board/GuideForm.js
  src/components/board/NoticesList.js
  src/components/board/NoticesListItem.js
  src/pages/board/BoardsPage.js
  src/pages/board/GuidePage.js
  src/pages/board/NoticesPage.js
  src/styles/components/board/BoardInfo.scss
  src/styles/components/board/BoardSideBar.scss
  src/styles/components/board/GuideForm.scss
  src/styles/components/board/NoticesList.scss
  src/styles/components/board/NoticesListItem.scss
  src/styles/style.scss
Labels: documentation, enhancement

#54 [Books] 페이지 추가 및 간단한 css 작업
  src/App.js
  src/components/books/BooksDetail.js
  src/components/books/BooksEditForm.js
  src/components/books/BooksList.js
  src/components/books/BooksWriteForm.js
  src/pages/BooksPage.js
  src/pages/books/BooksDetailPage.js
  src/pages/books/BooksEditPage.js
  src/pages/books/BooksListPage.js
  src/pages/books/BooksWritePage.js
  src/styles/components/books/BooksDetail.scss
  src/styles/components/books/BooksEditForm.scss
  src/styles/components/books/BooksList.scss
  src/styles/components/books/BooksWriteForm.scss
  src/styles/style.scss
Labels: documentation, enhancement

#55 [Admin] 로그인 페이지 추가
  package-lock.json
  package.json
  src/App.js
  src/components/auth/LoginForm.js
  src/container/auth/AuthForm.js
  src/index.js
  src/lib/api/auth.js
  src/lib/createRequestSaga.js
  src/modules/auth.js
  src/modules/index.js
  src/modules/loading.js
  src/modules/user.js
  src/pages/auth/LoginPage.js
  src/styles/components/auth/LoginForm.scss
  src/styles/style.scss
Labels: enhancement

#58 Feature/board
  src/App.js
  src/components/board/BoardList.js
  src/components/board/BoardNoticeListItem.js
  src/components/board/NoticesDetail.js
  src/components/board/NoticesList.js
  src/components/board/NoticesListItem.js
  src/pages/board/BooksDetailPage.js
  src/styles/components/board/NoticeDetail.scss
  src/styles/components/board/NoticesList.scss
  src/styles/components/board/NoticesListItem.scss
  src/styles/style.scss
Labels: documentation, enhancement

#65 [Admin] 마이페이지 추가 및 CSS 작업
  src/App.js
  src/components/auth/ProfileForm.js
  src/container/auth/Profile.js
  src/lib/api/auth.js
  src/pages/AdminPage.js
  src/pages/Home.js
  src/pages/auth/ProfilePage.js
  src/styles/components/auth/ProfileForm.scss
  src/styles/style.scss
Labels: documentation, enhancement

#66 blacklist 조회 및 등록 해제 구현
  src/components/blacklist/BlacklistForm.js
  src/components/blacklist/BlacklistItem.js
Labels: enhancement

#70 [Books] 상세 정보페이지 추가 및 css작업 및 axios연결
  src/App.js
  src/components/books/BooksDetail.js
  src/components/books/BooksEditForm.js
  src/components/books/BooksList.js
  src/components/books/BooksListItem.js
  src/components/books/BooksWriteForm.js
  src/styles/components/books/BooksDetail.scss
  src/styles/components/books/BooksEditForm.scss
  src/styles/components/books/BooksList.scss
  src/styles/components/books/BooksListItem.scss
  src/styles/components/books/BooksWriteForm.scss
  src/styles/style.scss
Labels: documentation, enhancement

#71 [Libraries] page추가
  src/App.js
  src/components/books/BooksEditForm.js
  src/components/libraries/LibrariesEdit.js
  src/components/libraries/LibrariesList.js
  src/components/libraries/LibrariesListItem.js
  src/components/libraries/LibrariesRuleForm.js
  src/pages/LibrariesRulePage.js
  src/pages/libraries/LibrariesEditPage.js
  src/pages/libraries/LibrariesListPage.js
  src/pages/libraries/LibrariesRulePage.js
  src/styles/components/libraries/LibrariesEdit.scss
  src/styles/components/libraries/LibrariesList.scss
  src/styles/components/libraries/LibrariesListItem.scss
  src/styles/components/libraries/LibrariesRuleForm.scss
  src/styles/style.scss
Labels: enhancement, good first issue

#73 [libraries] detail 페이지 작업 및 도서 수정페이지 수정
  src/App.js
  src/components/libraries/LibrariesDetail.js
  src/components/libraries/LibrariesEdit.js
  src/components/libraries/LibrariesListItem.js
  src/pages/libraries/LibrariesDetailPage.js
  src/styles/components/libraries/LibrariesDetail.scss
  src/styles/components/libraries/LibrariesEdit.scss
  src/styles/components/libraries/LibrariesListItem.scss
  src/styles/style.scss
Labels: documentation, enhancement

#76 Feature/lending list filter
  .vscode/launch.json
  src/components/lending/LendingListForm.js
  src/components/lending/LendingListItem.js
  src/components/lending/LendingSearchBox.js
  src/components/lending/LendingStatusFilter.js
  src/components/lending/LibraryFilter.js
  src/components/lending/SearchFilter.js
  src/lib/api/client.js
  src/pages/LendingPage.js
Labels: enhancement

#82 버튼 ui 구현
  src/components/common/Button.js
  src/components/lending/LendingListForm.js
  src/pages/LendingPage.js
Labels: documentation

#83 Feature/books/detail
  src/components/books/BooksDetail.js
  src/components/books/BooksEditForm.js
  src/components/books/BooksWriteForm.js
  src/styles/components/books/BooksDetail.scss
  src/styles/components/books/BooksListItem.scss
Labels: enhancement

#84 [Boards] filter적용 및 css 수정
  src/App.js
  src/components/board/BoardDetail.js
  src/components/board/BoardDetailForm.js
  src/components/board/BoardEditForm.js
  src/components/board/BoardInfo.js
  src/components/board/BoardList.js
  src/components/board/BoardNoticeListItem.js
  src/components/board/BoardWriteForm.js
  src/components/board/GuideForm.js
  src/components/board/NoticesDetail.js
  src/components/board/NoticesList.js
  src/components/board/NoticesListItem.js
  src/pages/board/BoardDetailPage.js
  src/styles/components/board/BoardDetail.scss
  src/styles/components/board/BoardDetailForm.scss
  src/styles/components/board/BoardInfo.scss
  src/styles/components/board/BoardList.scss
  src/styles/components/board/BoardListItem.scss
  src/styles/components/board/BoardSideBar.scss
  src/styles/components/board/GuideForm.scss
  src/styles/components/board/NoticeDetail.scss
  src/styles/components/board/NoticesList.scss
  src/styles/components/board/NoticesListItem.scss
  src/styles/style.scss
Labels: documentation, enhancement

#86 [board] 카카오 지도 api 추가 및 filter추가
  public/index.html
  src/components/board/BoardList.js
  src/components/board/BoardMap.js
  src/components/board/BoardWriteForm.js
  src/components/board/GuideForm.js
  src/components/board/NoticesList.js
  src/styles/components/board/BoardEditForm.scss
  src/styles/components/board/BoardMap.scss
  src/styles/components/board/BoardSideBar.scss
  src/styles/components/board/BoardWriteForm.scss
  src/styles/style.scss
Labels: enhancement

#88 [Libraries] 검색 기능 구현 및 모든 feature axios API 변경
  src/App.js
  src/components/blacklist/BlacklistForm.js
  src/components/blacklist/BlacklistItem.js
  src/components/board/BoardDetailForm.js
  src/components/board/BoardEditForm.js
  src/components/board/BoardList.js
  src/components/board/BoardWriteForm.js
  src/components/board/GuideForm.js
  src/components/board/NoticesDetail.js
  src/components/board/NoticesList.js
  src/components/books/BooksDetail.js
  src/components/books/BooksEditForm.js
  src/components/books/BooksList.js
  src/components/books/BooksWriteForm.js
  src/components/lending/LendingListForm.js
  src/components/libraries/LibrariesDetail.js
  src/components/libraries/LibrariesList.js
  src/components/libraries/LibrariesListItem.js
  src/components/libraries/LibrariesSearchFilter.js
  src/components/libraries/LibrariesWrite.js
  src/pages/libraries/LibrariesWritePage.js
  src/styles/components/board/BoardEditForm.scss
  src/styles/components/libraries/LibrariesDetail.scss
  src/styles/components/libraries/LibrariesList.scss
  src/styles/components/libraries/LibrariesListItem.scss
Labels: enhancement

#90 [board] 주석해제
  src/components/board/BoardInfo.js
  src/components/board/BoardList.js
  src/components/board/GuideForm.js
  src/styles/components/libraries/LibrariesDetail.scss
Labels: enhancement

#94 [Books] 도서 검색 기능 추가
  src/components/books/BookSearchFilter.js
  src/components/books/BooksList.js
Labels: enhancement

#95 관리자 메인 페이지 UI & 로그인 페이지 UI
  package.json
  public/img/pero-kalimero-9BJRGlqoIUk-unsplash.jpg
  src/components/Footer.js
  src/components/MainForm.js
  src/components/auth/LoginForm.js
  src/container/Main.js
  src/container/auth/AuthForm.js
  src/lib/api/auth.js
  src/pages/Home.js
  src/styles/common/footer.scss
  src/styles/components/auth/LoginForm.scss
  src/styles/components/auth/inputForm.scss
  src/styles/components/mainForm.scss
  src/styles/style.scss
Labels: documentation, enhancement

#99 [Books/Libraries] 리스트 css 작업
  src/components/books/BookSearchFilter.js
  src/components/books/BooksDetail.js
  src/components/books/BooksList.js
  src/components/books/BooksListItem.js
  src/styles/components/board/BoardDetailForm.scss
  src/styles/components/books/BooksDetail.scss
  src/styles/components/books/BooksList.scss
  src/styles/components/books/BooksListItem.scss
  src/styles/components/libraries/LibrariesDetail.scss
  src/styles/components/libraries/LibrariesListItem.scss
Labels: enhancement

#100 [Boards,Libraries,Books] css위주 작업
  src/components/board/Board.js
  src/components/board/BoardDetailForm.js
  src/components/board/BoardEditForm.js
  src/components/board/BoardInfo.js
  src/components/board/BoardList.js
  src/components/board/BoardNoticeListItem.js
  src/components/board/BoardSideBar.js
  src/components/board/BoardWriteForm.js
  src/components/board/GuideForm.js
  src/components/board/NoticesListItem.js
  src/components/books/BooksDetail.js
  src/components/books/BooksEditForm.js
  src/components/books/BooksList.js
  src/components/books/BooksWriteForm.js
  src/components/libraries/LibrariesDetail.js
  src/components/libraries/LibrariesEdit.js
  src/components/libraries/LibrariesList.js
  src/components/libraries/LibrariesRuleForm.js
  src/components/libraries/LibrariesWrite.js
  src/pages/board/BoardDetailPage.js
  src/pages/board/BoardEditPage.js
  src/pages/board/BoardListPage.js
  src/pages/board/BoardWritePage.js
  src/pages/board/BoardsPage.js
  src/pages/board/BooksDetailPage.js
  src/pages/board/GuidePage.js
  src/pages/board/NoticesPage.js
  src/pages/books/BooksDetailPage.js
  src/pages/books/BooksEditPage.js
  src/pages/books/BooksListPage.js
  src/pages/books/BooksWritePage.js
  src/pages/libraries/LibrariesDetailPage.js
  src/pages/libraries/LibrariesEditPage.js
  src/pages/libraries/LibrariesListPage.js
  src/pages/libraries/LibrariesRulePage.js
  src/pages/libraries/LibrariesWritePage.js
  src/styles/components/board/Board.scss
  src/styles/components/board/BoardDetailForm.scss
  src/styles/components/board/BoardEditForm.scss
  src/styles/components/board/BoardInfo.scss
  src/styles/components/board/BoardList.scss
  src/styles/components/board/BoardMap.scss
  src/styles/components/board/BoardSideBar.scss
  src/styles/components/board/BoardWriteForm.scss
  src/styles/components/board/GuideForm.scss
  src/styles/components/board/NoticeDetail.scss
  src/styles/components/board/NoticesList.scss
  src/styles/components/books/BooksDetail.scss
  src/styles/components/books/BooksEditForm.scss
  src/styles/components/books/BooksList.scss
  src/styles/components/books/BooksListItem.scss
  src/styles/components/books/BooksWriteForm.scss
  src/styles/components/libraries/LibrariesDetail.scss
  src/styles/components/libraries/LibrariesEdit.scss
  src/styles/components/libraries/LibrariesList.scss
  src/styles/components/libraries/LibrariesListItem.scss
  src/styles/components/libraries/LibrariesRuleForm.scss
  src/styles/components/libraries/LibrariesWrite.scss
  src/styles/style.scss
Labels: documentation, enhancement

#101 로그인 로그아웃 기능구현
  src/components/MainForm.js
  src/components/auth/ProfileForm.js
  src/container/Main.js
  src/container/auth/AuthForm.js
  src/index.js
  src/lib/api/auth.js
  src/lib/api/client.js
  src/lib/createRequestSaga.js
  src/modules/auth.js
  src/modules/index.js
  src/pages/Home.js
  src/pages/auth/FindIdPage.js
  src/pages/auth/FindPwPage.js
  src/pages/auth/LoginPage.js
  src/pages/auth/ProfilePage.js
Labels: documentation, enhancement
