Repository 247CloudLibrary/client-admin, pull requests merged in 2022-05, with the labels that each got.

#103 [Libraries] 이용 규정 수정 페이지 구현 및 전체적인 css 보정
  src/components/board/BoardEditForm.js
  src/components/board/BoardList.js
  src/components/board/BoardWriteForm.js
  src/components/books/BookSearchFilter.js
  src/components/books/BooksDetail.js
  src/components/books/BooksList.js
  src/components/books/BooksWriteForm.js
  src/components/libraries/LibrariesRuleForm.js
  src/components/libraries/LibrariesSearchFilter.js
  src/components/libraries/LibrariesWrite.js
  src/styles/components/board/Board.scss
  src/styles/components/board/BoardDetailForm.scss
  src/styles/components/board/BoardEditForm.scss
  src/styles/components/board/BoardList.scss
  src/styles/components/board/BoardWriteForm.scss
  src/styles/components/board/GuideForm.scss
  src/styles/components/board/NoticeDetail.scss
  src/styles/components/board/NoticesList.scss
  src/styles/components/books/BooksDetail.scss
  src/styles/components/books/BooksEditForm.scss
  src/styles/components/books/BooksList.scss
  src/styles/components/books/BooksListItem.scss
  src/styles/components/books/BooksWriteForm.scss
  src/styles/components/libraries/LibrariesDetail.scss
  src/styles/components/libraries/LibrariesEdit.scss
  src/styles/components/libraries/LibrariesList.scss
  src/styles/components/libraries/LibrariesListItem.scss
  src/styles/components/libraries/LibrariesRuleForm.scss
  src/styles/components/libraries/LibrariesWrite.scss
Labels: documentation, enhancement

#104 전체 유저 리스트 페이지
  public/img/janko-ferlic-sfL_QOnmy00-unsplash.jpg
  src/components/common/Footer.js
  src/components/common/Header.js
  src/pages/UserListPage.js
  src/styles/common/footer.scss
  src/styles/common/header.scss
  src/styles/components/auth/UserListForm.scss
  src/styles/style.scss
Labels: documentation, enhancement

#107 lendingListCss
  src/components/blacklist/BlacklistItem.js
  src/components/lending/LendingDetail.js
  src/pages/LendingPage.js
  src/styles/components/lending/LendingListForm.scss
  src/styles/components/lending/LendingListItem.scss
Labels: documentation

#108 Feature/boards
  src/components/board/BoardDetailForm.js
  src/components/board/BoardEditForm.js
  src/components/board/BoardInfo.js
  src/components/board/BoardList.js
  src/components/board/BoardMap.js
  src/components/board/BoardNoticeListItem.js
  src/components/board/BoardWriteForm.js
  src/components/board/GuideForm.js
  src/components/board/NoticesDetail.js
  src/components/board/NoticesList.js
  src/components/books/BooksDetail.js
  src/components/books/BooksEditForm.js
  src/components/books/BooksList.js
  src/components/books/BooksWriteForm.js
  src/components/libraries/LibrariesDetail.js
  src/components/libraries/LibrariesEdit.js
  src/components/libraries/LibrariesList.js
  src/components/libraries/LibrariesRuleForm.js
  src/components/libraries/LibrariesWrite.js
  src/pages/board/BoardEditPage.js
  src/styles/components/board/Board.scss
  src/styles/components/board/BoardDetailForm.scss
  src/styles/components/board/BoardEditForm.scss
  src/styles/components/board/BoardInfo.scss
  src/styles/components/board/BoardList.scss
  src/styles/components/board/BoardListItem.scss
  src/styles/components/board/BoardWriteForm.scss
  src/styles/components/board/GuideForm.scss
  src/styles/components/board/NoticeDetail.scss
  src/styles/components/board/NoticesList.scss
  src/styles/components/books/BooksDetail.scss
  src/styles/components/books/BooksEditForm.scss
  src/styles/components/books/BooksList.scss
  src/styles/components/books/BooksWriteForm.scss
  src/styles/components/libraries/LibrariesDetail.scss
  src/styles/components/libraries/LibrariesEdit.scss
  src/styles/components/libraries/LibrariesList.scss
  src/styles/components/libraries/LibrariesRuleForm.scss
  src/styles/components/libraries/LibrariesWrite.scss
Labels: documentation, enhancement

#109 blacklist 및 lendingList css 수정
  src/components/blacklist/BlacklistForm.js
  src/components/blacklist/BlacklistItem.js
  src/components/lending/LendingDetail.js
  src/context/lendingContext.js
  src/pages/BlacklistPage.js
  src/pages/LendingPage.js
  src/styles/components/lending/BlackListItem.scss
  src/styles/components/lending/BlacklistForm.scss
  src/styles/components/lending/LendingListForm.scss
Labels: documentation

#110 아이디 찾기 비밀번호 찾기 추가
  src/components/auth/FindIdForm.js
  src/components/auth/FindPwForm.js
  src/container/auth/FindId.js
  src/container/auth/FindPw.js
  src/styles/components/auth/FindIdForm.scss
  src/styles/components/auth/FindPwForm.scss
Labels: documentation, enhancement

#111 header,footer 추가
  src/components/board/Board.js
  src/components/board/BoardDetailForm.js
  src/components/board/BoardEditForm.js
  src/components/board/BoardInfo.js
  src/components/board/BoardList.js
  src/components/board/BoardWriteForm.js
  src/components/board/GuideForm.js
  src/components/board/NoticesDetail.js
  src/components/board/NoticesList.js
  src/components/books/BooksDetail.js
  src/components/books/BooksEditForm.js
  src/components/books/BooksList.js
  src/components/books/BooksWriteForm.js
  src/components/libraries/LibrariesDetail.js
  src/components/libraries/LibrariesEdit.js
  src/components/libraries/LibrariesList.js
  src/components/libraries/LibrariesRuleForm.js
  src/components/libraries/LibrariesWrite.js
  src/pages/board/BoardDetailPage.js
  src/pages/board/BoardEditPage.js
  src/pages/board/BoardListPage.js
  src/pages/board/BoardWritePage.js
  src/pages/board/BoardsPage.js
  src/pages/board/BooksDetailPage.js
  src/pages/board/GuidePage.js
  src/pages/board/NoticesPage.js
  src/styles/components/board/BoardDetailForm.scss
  src/styles/components/board/NoticeDetail.scss
  src/styles/components/books/BooksEditForm.scss
  src/styles/components/books/BooksWriteForm.scss
  src/styles/components/libraries/LibrariesEdit.scss
  src/styles/components/libraries/LibrariesList.scss
Labels: documentation, enhancement

#115 lendingDetail css 수정
  src/components/lending/LendingDetail.js
  src/styles/components/lending/LendingDetail.scss
  src/styles/components/lending/LendingListForm.scss
Labels: documentation

#113 관리자 프로필 수정 구현
  src/components/auth/ProfileForm.js
  src/styles/common/footer.scss
  src/styles/components/auth/UserListForm.scss
Labels: enhancement

#117 비밀번호 변경 추가 & 도서 검색 추가
  src/App.js
  src/components/MainForm.js
  src/components/auth/ChangePasswordForm.js
  src/components/common/SearchBar.js
  src/container/Main.js
  src/pages/auth/ChangePasswordPage.js
  src/styles/common/serachBar.scss
  src/styles/components/auth/ChangePassword.scss
  src/styles/style.scss
Labels: documentation, enhancement

#120 s3 이미지 업로드 구현
  package-lock.json
  package.json
  src/components/books/BooksEditForm.js
  src/components/books/ImgUpload.js
Labels: documentation, enhancement

#121 lending header에 token추가
  src/components/lending/LendingDetail.js
  src/components/lending/LendingListForm.js
  src/pages/LendingPage.js
  src/styles/components/lending/LendingDetail.scss
  src/styles/components/lending/LendingListForm.scss
  src/styles/components/lending/LendingListItem.scss
Labels: enhancement

#123 README 틀 완성
  README.md
Labels: documentation
